server:
  port: 8070

external-system:
  product:
    url: localhost:8090

order:
  mq:
    url: tcp://localhost:61616
    username: admin
    password: admin
    queue: message-queue

new-order:
  mq:
    url: tcp://localhost:61616
    username: admin
    password: admin
    queue: new-order

order-updates:
  mq:
    url: tcp://localhost:61616
    username: admin
    password: admin
    queue: order-updates

product-sell:
  mq:
    url: tcp://localhost:61616
    username: admin
    password: admin
    queue: product-sell
